
namespace Services
{
    public enum CountieIds
    {
        Aitkin = 1,
        Anoka = 2,
        Becker = 3,
        Beltrami = 4,
        Benton = 5,
        BigStone = 6,
        BlueEarth = 7,
        Brown = 8,
        Carlton = 9,
        Carver = 10,
        Cass = 11,
        Chippewa = 12,
        Chisago = 13,
        Clay = 14,
        Clearwater = 15,
        Cook = 16,
        Cottonwood = 17,
        CrowWing = 18,
        Dakota = 19,
        Dodge = 20,
        Douglas = 21,
        Faribault = 22,
        Fillmore = 23,
        Freeborn = 24,
        Goodhue = 25,
        Grant = 26,
        Hennepin = 27,
        Houston = 28,
        Hubbard = 29,
        Isanti = 30,
        Itasca = 31,
        Jackson = 32,
        Kanabec = 33,
        Kandiyohi = 34,
        Kittson = 35,
        Koochiching = 36,
        LacquiParle = 37,
        Lake = 38,
        LakeoftheWood = 39,
        LeSueur = 40,
        Lincoln = 41,
        Lyon = 42,
        McLeod = 43,
        Mahnomen = 44,
        Marshall = 45,
        Martin = 46,
        Meeker = 47,
        MilleLacs = 48,
        Morrison = 49,
        Mower = 50,
        Murray = 51,
        Nicollet = 52,
        Nobles = 53,
        Norman = 54,
        Olmsted = 55,
        OtterTail = 56,
        Pennington = 57,
        Pine = 58,
        Pipestone = 59,
        Polk = 60,
        Pope = 61,
        Ramsey = 62,
        RedLake = 63,
        Redwood = 64,
        Renville = 65,
        Rice = 66,
        Rock = 67,
        Roseau = 68,
        StLouis = 69,
        Scott = 70,
        Sherburne = 71,
        Sibley = 72,
        Stearns = 73,
        Steele = 74,
        Stevens = 75,
        Swift = 76,
        Todd = 77,
        Traverse = 78,
        Wabasha = 79,
        Wadena = 80,
        Waseca = 81,
        Washington = 82,
        Watonwan = 83,
        Wilkin = 84,
        Winona = 85,
        Wright = 86,
        YellowMedicine = 87
    }

    public static class Counties
    {
        public static readonly string Aitkin = "Aitkin";
        public static readonly string Anoka = "Anoka";
        public static readonly string Becker = "Becker";
        public static readonly string Beltrami = "Beltrami";
        public static readonly string Benton = "Benton";
        public static readonly string BigStone = "Big Stone";
        public static readonly string BlueEarth = "Blue Earth";
        public static readonly string Brown = "Brown";
        public static readonly string Carlton = "Carlton";
        public static readonly string Carver = "Carver";
        public static readonly string Cass = "Cass";
        public static readonly string Chippewa = "Chippewa";
        public static readonly string Chisago = "Chisago";
        public static readonly string Clay = "Clay";
        public static readonly string Clearwater = "Clearwater";
        public static readonly string Cook = "Cook";
        public static readonly string Cottonwood = "Cottonwood";
        public static readonly string CrowWing = "Crow Wing";
        public static readonly string Dakota = "Dakota";
        public static readonly string Dodge = "Dodge";
        public static readonly string Douglas = "Douglas";
        public static readonly string Faribault = "Faribault";
        public static readonly string Fillmore = "Fillmore";
        public static readonly string Freeborn = "Freeborn";
        public static readonly string Goodhue = "Goodhue";
        public static readonly string Grant = "Grant";
        public static readonly string Hennepin = "Hennepin";
        public static readonly string Houston = "Houston";
        public static readonly string Hubbard = "Hubbard";
        public static readonly string Isanti = "Isanti";
        public static readonly string Itasca = "Itasca";
        public static readonly string Jackson = "Jackson";
        public static readonly string Kanabec = "Kanabec";
        public static readonly string Kandiyohi = "Kandiyohi";
        public static readonly string Kittson = "Kittson";
        public static readonly string Koochiching = "Koochiching";
        public static readonly string LacquiParle = "Lac qui Parle";
        public static readonly string Lake = "Lake";
        public static readonly string LakeoftheWood = "Lake of the Woods";
        public static readonly string LeSueur = "Le Sueur";
        public static readonly string Lincoln = "Lincoln";
        public static readonly string Lyon = "Lyon";
        public static readonly string McLeod = "McLeod";
        public static readonly string Mahnomen = "Mahnomen";
        public static readonly string Marshall = "Marshall";
        public static readonly string Martin = "Martin";
        public static readonly string Meeker = "Meeker";
        public static readonly string MilleLacs = "Mille Lacs";
        public static readonly string Morrison = "Morrison";
        public static readonly string Mower = "Mower";
        public static readonly string Murray = "Murray";
        public static readonly string Nicollet = "Nicollet";
        public static readonly string Nobles = "Nobles";
        public static readonly string Norman = "Norman";
        public static readonly string Olmsted = "Olmsted";
        public static readonly string OtterTail = "Otter Tail";
        public static readonly string Pennington = "Pennington";
        public static readonly string Pine = "Pine";
        public static readonly string Pipestone = "Pipestone";
        public static readonly string Polk = "Polk";
        public static readonly string Pope = "Pope";
        public static readonly string Ramsey = "Ramsey";
        public static readonly string RedLake = "Red Lake";
        public static readonly string Redwood = "Redwood";
        public static readonly string Renville = "Renville";
        public static readonly string Rice = "Rice";
        public static readonly string Rock = "Rock";
        public static readonly string Roseau = "Roseau";
        public static readonly string StLouis = "St Louis";
        public static readonly string Scott = "Scott";
        public static readonly string Sherburne = "Sherburne";
        public static readonly string Sibley = "Sibley";
        public static readonly string Stearns = "Stearns";
        public static readonly string Steele = "Steele";
        public static readonly string Stevens = "Stevens";
        public static readonly string Swift = "Swift";
        public static readonly string Todd = "Todd";
        public static readonly string Traverse = "Traverse";
        public static readonly string Wabasha = "Wabasha";
        public static readonly string Wadena = "Wadena";
        public static readonly string Waseca = "Waseca";
        public static readonly string Washington = "Washington";
        public static readonly string Watonwan = "Watonwan";
        public static readonly string Wilkin = "Wilkin";
        public static readonly string Winona = "Winona";
        public static readonly string Wright = "Wright";
        public static readonly string YellowMedicine = "Yellow Medicine";
    }
}
